[package]
name = "mini_exercism"
version = "0.1.0"
authors = [ "Charles Lechasseur <shiftingbeard@gmx.com>" ]
edition = "2021"

readme = "README.md"
license = "MIT"

homepage = "https://github.com/clechasseur/mini_exercism#readme"
repository = "https://github.com/clechasseur/mini_exercism"
documentation = "https://docs.rs/mini_exercism/"

description = "Minimalistic Rust library to interact with the Exercism.org APIs"

keywords = [ "api", "rest", "http", "exercism" ]
categories = [ "api bindings", "asynchronous" ]

include = [ "src/**/*", "tests/**/*", "build.rs", "LICENSE", "README.md" ]

[package.metadata.docs.rs]
all-features = true
targets = [ "x86_64-unknown-linux-gnu" ]
rustc-args = [ "--cfg", "docsrs" ]

[features]
cli = []

[dependencies]
bytes = "1.4.0"
derive_builder = "0.12.0"
futures = "0.3.28"
mockall_double = "0.3.0"
paste = "1.0.14"
reqwest = { version = "0.11.20", features = ["json", "stream"] }
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
strum = "0.25.0"
strum_macros = "0.25.2"
thiserror = "1.0.47"

[dev-dependencies]
assert_matches = "1.5.0"
mockall = "0.11.4"
serial_test = "2.0.0"
tokio = { version = "1.32.0", features = ["rt", "rt-multi-thread", "macros", "test-util"] }
wiremock = "0.5.19"
wiremock_logical_matchers = "0.1.2"

[build-dependencies]
rustc_version = "0.4.0"
