[package]
name = "mini_exercism"
version = "2.1.0"
authors = [ "Charles Lechasseur <shiftingbeard@gmx.com>" ]
edition = "2021"
rust-version = "1.63"

readme = "README.md"
license = "MIT"

homepage = "https://github.com/clechasseur/mini_exercism#readme"
repository = "https://github.com/clechasseur/mini_exercism"
documentation = "https://docs.rs/mini_exercism/"

description = "Minimalistic Rust library to interact with the Exercism.org APIs"

keywords = [ "api", "rest", "http", "exercism" ]
categories = [ "api-bindings", "asynchronous" ]

include = [ "src/**/*", "tests/**/*", "build.rs", "LICENSE", "README.md" ]

[package.metadata.docs.rs]
all-features = true
targets = [ "x86_64-unknown-linux-gnu" ]
rustc-args = [ "--cfg", "docsrs" ]

[features]
cli = []

[dependencies]
bytes = "1.5.0"
derive_builder = "0.13.0"
futures = "0.3.30"
mockall_double = "0.3.1"
paste = "1.0.14"
reqwest = { version = "0.11.24", features = ["json", "stream"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
strum = "0.25.0"
strum_macros = "0.25.3"
thiserror = "1.0.56"

[dev-dependencies]
anyhow = "1.0.79"
assert_matches = "1.5.0"
itertools = "0.12.1"
mockall = "0.12.1"
serial_test = "3.0.0"
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "macros", "test-util"] }
wiremock = "0.5.22"
wiremock_logical_matchers = "0.5.1"

[build-dependencies]
rustc_version = "0.4.0"
