[package]
name = "mini_exercism"
version = "1.1.0"
authors = [ "Charles Lechasseur <shiftingbeard@gmx.com>" ]
edition = "2021"
rust-version = "1.63"

readme = "README.md"
license = "MIT"

homepage = "https://github.com/clechasseur/mini_exercism#readme"
repository = "https://github.com/clechasseur/mini_exercism"
documentation = "https://docs.rs/mini_exercism/"

description = "Minimalistic Rust library to interact with the Exercism.org APIs"

keywords = [ "api", "rest", "http", "exercism" ]
categories = [ "api-bindings", "asynchronous" ]

include = [ "src/**/*", "tests/**/*", "build.rs", "LICENSE", "README.md" ]

[package.metadata.docs.rs]
all-features = true
targets = [ "x86_64-unknown-linux-gnu" ]
rustc-args = [ "--cfg", "docsrs" ]

[features]
cli = []

[dependencies]
bytes = "1.2"
derive_builder = ">= 0.11, < 0.13"
futures = "0.3.29"
mockall_double = ">= 0.2, < 0.4"
paste = "1"
reqwest = { version = "0.11.2", features = ["json", "stream"] }
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1"
strum = ">= 0.13, < 0.26"
strum_macros = ">= 0.13, < 0.26"
thiserror = "1.0.2"

[dev-dependencies]
anyhow = "1.0.75"
assert_matches = "1.5.0"
mockall = "0.11.4"
serial_test = "2.0.0"
tokio = { version = "1.32.0", features = ["rt", "rt-multi-thread", "macros", "test-util"] }
wiremock = "0.5.19"
wiremock_logical_matchers = "0.1.3"

[build-dependencies]
rustc_version = "0.4.0"
