[package]
name = "mini_exercism"
version = "0.1.0"
edition = "2021"

[features]
cli = []

[dependencies]
derive_builder = "0.12.0"
futures = "0.3.28"
mockall_double = "0.3.0"
paste = "1.0.14"
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
strum = "0.25.0"
strum_macros = "0.25.2"
thiserror = "1.0.47"

[dev-dependencies]
assert_matches = "1.5.0"
mockall = "0.11.4"
serial_test = "2.0.0"
tokio = { version = "1.32.0", features = ["rt", "macros", "test-util"] }
wiremock = "0.5.19"
wiremock_logical_matchers = "0.1.2"
