name: Security audit

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  audit-check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run security audit
        # Note: the action below is a temporary fork of rustsec/audit-check; it could be
        # replaced if, at some point, rustsec/audit-check is updated to use Node 20.
        uses: clechasseur/rustsec-audit-check@b7dc4ebf0c78ffba0982f75a53d230f48c2a76e9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
