name: Security audit

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  audit-check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v1

      - name: Run security audit
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if we need to audit MSRV cargo files
        id: check_msrv_cargo_files
        uses: andstor/file-existence-action@v2
        with:
          files: "Cargo.lock.msrv, Cargo.toml.msrv"

      - name: Install MSRV cargo files
        if: ${{ steps.check_msrv_cargo_files.outputs.files_exists == 'true' }}
        run: just pre-msrv

      - name: Run security audit for MSRV cargo files
        if: ${{ steps.check_msrv_cargo_files.outputs.files_exists == 'true' }}
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
